apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: words
build:
  artifacts:
  - image: words
deploy:
  kubectl:
    manifests:
    - k8s/words.yaml
portForward:
  - resourceType: service
    resourceName: words
    port: 50051
    localPort: 3000