apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: distributed-codenames
requires:
  - path: src/games
  - path: src/games-bff
  - path: src/games-spa
  - path: src/lobbies
  - path: src/lobbies-spa
  - path: src/players
  - path: src/players-spa
  - path: src/words
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
