apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: distributed-codenames
requires:
  - path: services/games
  - path: services/games-bff
  - path: services/games-spa
  - path: services/lobbies
  - path: services/lobbies-spa
  - path: services/players
  - path: services/players-spa
  - path: services/words
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
