apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: default-ingress
deploy:
  kubectl:
    manifests:
      - k8s/ingress.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: games
requires:
  - configs:
      - words
build:
  artifacts:
    - image: games
      context: services/games
      ko: {}
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/games.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: games-bff
requires:
  - configs:
      - games
build:
  artifacts:
    - image: games-bff
      context: services/games-bff
      buildpacks:
        builder: paketobuildpacks/builder:base
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/games-bff.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: games-spa
requires:
  - configs:
      - games-bff
build:
  artifacts:
    - image: games-spa
      context: services/games-spa
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/games-spa.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: lobbies
build:
  artifacts:
    - image: lobbies
      context: services/lobbies
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/lobbies.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: lobbies-spa
requires:
  - configs:
      - lobbies
build:
  artifacts:
    - image: lobbies-spa
      context: services/lobbies-spa
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/lobbies-spa.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: players
build:
  artifacts:
    - image: players
      context: services/players
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/players.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: players-spa
requires:
  - configs:
      - players
build:
  artifacts:
    - image: players-spa
      context: services/players-spa
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/players-spa.yaml
---
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: words
build:
  artifacts:
    - image: words
      context: services/words
      ko: {}
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/words.yaml
