apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: default-ingress
manifests:
  rawYaml:
    - k8s/ingress.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: games
requires:
  - configs:
      - words
build:
  artifacts:
    - image: games
      context: services/games
      ko: {}
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/games.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: games-bff
requires:
  - configs:
      - games
build:
  artifacts:
    - image: games-bff
      context: services/games-bff
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/games-bff.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: games-spa
requires:
  - configs:
      - games-bff
build:
  artifacts:
    - image: games-spa
      context: services/games-spa
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/games-spa.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: lobbies
build:
  artifacts:
    - image: lobbies
      context: services/lobbies
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/lobbies.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: lobbies-spa
requires:
  - configs:
      - lobbies
build:
  artifacts:
    - image: lobbies-spa
      context: services/lobbies-spa
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/lobbies-spa.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: players
build:
  artifacts:
    - image: players
      context: services/players
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/players.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: players-spa
requires:
  - configs:
      - players
build:
  artifacts:
    - image: players-spa
      context: services/players-spa
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/players-spa.yaml
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: words
build:
  artifacts:
    - image: words
      context: services/words
      ko: {}
  local:
    concurrency: 0
manifests:
  rawYaml:
    - k8s/words.yaml
deploy:
  kubectl: {}
