// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: words.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WordsServiceClient is the client API for WordsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordsServiceClient interface {
	GetWords(ctx context.Context, in *WordsRequest, opts ...grpc.CallOption) (*WordsResponse, error)
}

type wordsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordsServiceClient(cc grpc.ClientConnInterface) WordsServiceClient {
	return &wordsServiceClient{cc}
}

func (c *wordsServiceClient) GetWords(ctx context.Context, in *WordsRequest, opts ...grpc.CallOption) (*WordsResponse, error) {
	out := new(WordsResponse)
	err := c.cc.Invoke(ctx, "/distributed_codenames.WordsService/GetWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordsServiceServer is the server API for WordsService service.
// All implementations must embed UnimplementedWordsServiceServer
// for forward compatibility
type WordsServiceServer interface {
	GetWords(context.Context, *WordsRequest) (*WordsResponse, error)
	mustEmbedUnimplementedWordsServiceServer()
}

// UnimplementedWordsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWordsServiceServer struct {
}

func (UnimplementedWordsServiceServer) GetWords(context.Context, *WordsRequest) (*WordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWords not implemented")
}
func (UnimplementedWordsServiceServer) mustEmbedUnimplementedWordsServiceServer() {}

// UnsafeWordsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordsServiceServer will
// result in compilation errors.
type UnsafeWordsServiceServer interface {
	mustEmbedUnimplementedWordsServiceServer()
}

func RegisterWordsServiceServer(s grpc.ServiceRegistrar, srv WordsServiceServer) {
	s.RegisterService(&WordsService_ServiceDesc, srv)
}

func _WordsService_GetWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordsServiceServer).GetWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/distributed_codenames.WordsService/GetWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordsServiceServer).GetWords(ctx, req.(*WordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordsService_ServiceDesc is the grpc.ServiceDesc for WordsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distributed_codenames.WordsService",
	HandlerType: (*WordsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWords",
			Handler:    _WordsService_GetWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "words.proto",
}
