apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: games
build:
  artifacts:
  - image: games
deploy:
  kubectl:
    manifests:
    - k8s/games.yaml
portForward:
  - resourceType: service
    resourceName: games
    port: 50051
    localPort: 4000
