apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-bff
spec:
  selector:
    matchLabels:
      app: games-bff
  template:
    metadata:
      labels:
        app: games-bff
    spec:
      containers:
        - name: server
          image: games-bff
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 10
          env:
            - name: GAMES_HOST
              value: "games:50051"
            - name: HOST_PREFIX
              value: "/api/games"
            - name: NATS_HOST
              value: "my-nats"
---
apiVersion: v1
kind: Service
metadata:
  name: games-bff
spec:
  selector:
    app: games-bff
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: games-bff-mapping
spec:
  prefix: /api/games/
  service: games-bff
  allow_upgrade:
    - websocket
