FROM mcr.microsoft.com/dotnet/sdk:5.0 AS base
WORKDIR /app
COPY *.csproj .
RUN dotnet restore -r linux-x64

FROM base AS build
WORKDIR /app
COPY . .
RUN dotnet publish -c release -o out -r linux-x64 --self-contained true \
    --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true

FROM mcr.microsoft.com/dotnet/runtime-deps:5.0
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["./api"]