apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies
spec:
  selector:
    matchLabels:
      app: lobbies
  template:
    metadata:
      labels:
        app: lobbies
    spec:
      containers:
        - name: server
          image: lobbies
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
          env:
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "true"
            - name: GAMES_HOST
              value: "http://games:50051"
            - name: HOST_PREFIX
              value: "/api/lobbies"
            - name: PLAYERS_HOST
              value: "http://players"
            - name: REDIS_HOST
              value: "lobbies-redis-master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobbies-redis
                  key: redis-password
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies
spec:
  selector:
    app: lobbies
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: lobbies-mapping
  labels:
    defaulthost: host
spec:
  prefix: /api/lobbies/
  service: lobbies
  allow_upgrade:
    - websocket
