apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: games-bff
build:
  artifacts:
    - image: games-bff
      buildpacks:
        builder: "paketobuildpacks/builder:base"
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/games-bff.yaml
