apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobbies-spa
spec:
  selector:
    matchLabels:
      app: lobbies-spa
  template:
    metadata:
      labels:
        app: lobbies-spa
    spec:
      containers:
        - name: server
          image: lobbies-spa
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lobbies-spa
spec:
  selector:
    app: lobbies-spa
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: lobbies-spa-mapping
spec:
  prefix: /lobbies
  service: lobbies-spa
