apiVersion: apps/v1
kind: Deployment
metadata:
  name: games
spec:
  selector:
    matchLabels:
      app: games
  template:
    metadata:
      labels:
        app: games
    spec:
      containers:
        - name: server
          image: games
          ports:
            - containerPort: 50051
          livenessProbe:
            grpc:
              port: 50051
          env:
            - name: NATS_HOST
              value: "my-nats"
            - name: REDIS_HOST
              value: "games-redis-master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: games-redis
                  key: redis-password
            - name: WORDS_ADDRESS
              value: "words:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: games
spec:
  type: ClusterIP
  selector:
    app: games
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
