name: CI
on:
  push:
    branches: [main, feature/github-actions-ko-and-pack]
    paths-ignore:
      - "docs/**"
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "distributed-codenames"
      - name: Setup Ko
        uses: imjasonh/setup-ko@v0.4
      - name: Setup Pack
        uses: buildpacks/github-actions/setup-pack@v4.4.0
      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Render manifests
        run: |
          cd $GITHUB_WORKSPACE/distributed-codenames
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          skaffold render --default-repo=ghcr.io/deesejohn \
            --digest-source='render' \
            --output $GITHUB_WORKSPACE/manifests.yaml \
            --offline=true
      - name: Checkout cluster
        uses: actions/checkout@v2
        with:
          path: "distributed-codenames-cluster"
          repository: "deesejohn/distributed-codenames-cluster"
          token: ${{ secrets.CLUSTER_PAT }}
      - name: Commit manifests
        run: |
          cd $GITHUB_WORKSPACE/distributed-codenames-cluster
          mv $GITHUB_WORKSPACE/manifests.yaml releases/manifests.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release/$GITHUB_SHA
          git add releases/manifests.yaml
          git commit -m "rendered manifests"
          git push -u origin release/$GITHUB_SHA
