name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: $GITHUB_WORKSPACE/distributed-codenames
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: $GITHUB_WORKSPACE/distributed-codenames/go.work
      - name: Setup Ko
        uses: imjasonh/setup-ko@v0.6
      - name: Setup Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Restore Skaffold cache
        id: cache-skaffold-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.skaffold/
          key: ${{ runner.os }}-skaffold
      - name: Render manifests
        run: |
          cd $GITHUB_WORKSPACE/distributed-codenames
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          skaffold render --default-repo=ghcr.io/deesejohn \
            --digest-source='local' \
            --output $GITHUB_WORKSPACE/manifests.yaml \
            --offline=true
      - name: Save Skaffold cache
        id: cache-skaffold-save
        uses: actions/cache/save@v3
        with:
          path: ~/.skaffold/
          key: ${{ steps.cache-skaffold-restore.outputs.cache-primary-key }}
      - name: Checkout cluster
        uses: actions/checkout@v4
        with:
          path: $GITHUB_WORKSPACE/distributed-codenames-cluster
          repository: deesejohn/distributed-codenames-cluster
          token: ${{ secrets.CLUSTER_PAT }}
      - name: Commit manifests
        run: |
          cd $GITHUB_WORKSPACE/distributed-codenames-cluster
          mv $GITHUB_WORKSPACE/manifests.yaml releases/manifests.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release/$GITHUB_SHA
          git add releases/manifests.yaml
          git commit -m "rendered manifests"
          git push -u origin release/$GITHUB_SHA
