name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: src
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: src/go.work
      - name: Setup Ko
        uses: ko-build/setup-ko@v0.6
      - name: Setup Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Restore Skaffold cache
        id: cache-skaffold-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/.skaffold/
          key: ${{ runner.os }}-skaffold
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Render manifests
        working-directory: src
        run: |
          skaffold render \
            --default-repo=ghcr.io/deesejohn \
            --digest-source='local' \
            --output ../manifests.yaml \
            --offline=true
      - name: Save Skaffold cache
        id: cache-skaffold-save
        uses: actions/cache/save@v3
        with:
          path: ~/.skaffold/
          key: ${{ steps.cache-skaffold-restore.outputs.cache-primary-key }}
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: src
        run: |
          gh release create "release-$(git rev-parse --short HEAD)" --generate-notes ../manifests.yaml
      - name: Checkout cluster
        uses: actions/checkout@v4
        with:
          path: cluster
          repository: deesejohn/distributed-codenames-cluster
          token: ${{ secrets.CLUSTER_PAT }}
      - name: Commit manifests
        working-directory: cluster
        run: |
          mv ../manifests.yaml releases/manifests.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release/$GITHUB_SHA
          git add releases/manifests.yaml
          git commit -m "rendered manifests"
          git push -u origin release/$GITHUB_SHA
